//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmdletHelpEditor.API.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlMamlTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlMamlTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmdletHelpEditor.API.Templates.XmlMamlTemplate", typeof(XmlMamlTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;command:parameter required=&quot;{0}&quot; variableLength=&quot;{1}&quot; globbing=&quot;{2}&quot; pipelineInput=&quot;{3}&quot; position=&quot;{4}&quot;&gt;&lt;maml:name&gt;{5}&lt;/maml:name&gt;&lt;maml:description&gt;{6}&lt;/maml:description&gt;{7}&lt;dev:type&gt;&lt;maml:name&gt;{8}&lt;/maml:name&gt;&lt;maml:uri/&gt;&lt;/dev:type&gt;&lt;dev:defaultValue&gt;{9}&lt;/dev:defaultValue&gt;&lt;/command:parameter&gt;.
        /// </summary>
        internal static string CommandParam {
            get {
                return ResourceManager.GetString("CommandParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;command:parameterValue required=&quot;{0}&quot; variableLength=&quot;{1}&quot;&gt;{2}&lt;/command:parameterValue&gt;.
        /// </summary>
        internal static string CommandParamValue {
            get {
                return ResourceManager.GetString("CommandParamValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;command:syntaxItem&gt;&lt;maml:name&gt;{0}&lt;/maml:name&gt;&lt;/command:syntaxItem&gt;.
        /// </summary>
        internal static string CommandSyntax {
            get {
                return ResourceManager.GetString("CommandSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--Generated by PS Cmdlet Help Editor--&gt;
        ///&lt;command:details&gt;&lt;command:name&gt;{0}&lt;/command:name&gt;&lt;maml:description&gt;{1}&lt;/maml:description&gt;&lt;maml:copyright&gt;&lt;maml:para /&gt;&lt;/maml:copyright&gt;&lt;command:verb&gt;{2}&lt;/command:verb&gt;&lt;command:noun&gt;{3}&lt;/command:noun&gt;&lt;dev:version /&gt;&lt;/command:details&gt;&lt;maml:description&gt;{4}&lt;/maml:description&gt;.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;command:terminatingErrors&gt;&lt;/command:terminatingErrors&gt;&lt;command:nonTerminatingErrors&gt;&lt;/command:nonTerminatingErrors&gt;.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;command:example&gt;&lt;maml:title&gt;--------------------------  {0}  --------------------------&lt;/maml:title&gt;&lt;maml:introduction&gt;&lt;maml:paragraph&gt;PS C:\\&amp;gt;&lt;/maml:paragraph&gt;&lt;/maml:introduction&gt;&lt;dev:code&gt;{1}&lt;/dev:code&gt;&lt;dev:remarks&gt;{2}&lt;maml:para /&gt;&lt;maml:para /&gt;&lt;maml:para&gt;{3}&lt;/maml:para&gt;&lt;/dev:remarks&gt;&lt;command:commandLines&gt;&lt;command:commandLine&gt;&lt;command:commandText&gt;&lt;maml:para /&gt;&lt;/command:commandText&gt;&lt;/command:commandLine&gt;&lt;/command:commandLines&gt;&lt;/command:example&gt;.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;command:inputType&gt;&lt;dev:type&gt;&lt;maml:name&gt;{0}&lt;/maml:name&gt;&lt;maml:uri&gt;{1}&lt;/maml:uri&gt;&lt;maml:description/&gt;&lt;/dev:type&gt;&lt;maml:description&gt;{2}&lt;/maml:description&gt;&lt;/command:inputType&gt;.
        /// </summary>
        internal static string InputType {
            get {
                return ResourceManager.GetString("InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;maml:alertSet&gt;&lt;maml:title&gt;&lt;/maml:title&gt;&lt;maml:alert&gt;{0}&lt;/maml:alert&gt;&lt;/maml:alertSet&gt;.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;maml:navigationLink&gt;&lt;maml:linkText&gt;{0}&lt;/maml:linkText&gt;&lt;maml:uri&gt;{1}&lt;/maml:uri&gt;&lt;/maml:navigationLink&gt;.
        /// </summary>
        internal static string RelatedLink {
            get {
                return ResourceManager.GetString("RelatedLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;command:returnValue&gt;&lt;dev:type&gt;&lt;maml:name&gt;{0}&lt;/maml:name&gt;&lt;maml:uri&gt;{1}&lt;/maml:uri&gt;&lt;maml:description/&gt;&lt;/dev:type&gt;&lt;maml:description&gt;{2}&lt;/maml:description&gt;&lt;/command:returnValue&gt;.
        /// </summary>
        internal static string ReturnType {
            get {
                return ResourceManager.GetString("ReturnType", resourceCulture);
            }
        }
    }
}
